name: Horusec Scan

on: [push]

jobs:
  checking_code:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - uses: actions/checkout@v2

      - name: Run Horusec
        id: run_horusec
        with:
          arguments: -c=horusec-config.json -p ./
