name: Horusec Scan

on: [push]

jobs:
  checking_code:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - uses: actions/checkout@v2
      - name: Run Horusec
        id: run_horusec
        run: |
              curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
              horusec start -p="./" -e="true" --config-file-path string   Path of the configuration file (default "/home/runner/work/Juice/Juice/horusec-config.json")
