name: Horusec Scan

on: [push]

jobs:
  checking_code:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - uses: actions/checkout@v2
      - name: Run Horusec
        id: run_horusec
        run: |
              horusec start -p --config-file-path=/home/gel/juice-shop/horusec-config.json
